# Generated by Django 4.0.3 on 2022-05-23 16:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating_andComments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.FloatField(verbose_name='Рейтинг')),
                ('comment', models.TextField(verbose_name='Комментарий')),
            ],
        ),
        migrations.AddField(
            model_name='tovar',
            name='rating',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='tovar',
            name='rating_from_user',
            field=models.ManyToManyField(related_name='rating_user', through='homepage.Rating_andComments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='store_rating',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='user_rating_and_comment_for_tovar',
            field=models.ManyToManyField(related_name='rating_tovar', through='homepage.Rating_andComments', to='homepage.tovar'),
        ),
        migrations.AddField(
            model_name='rating_andcomments',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.tovar', verbose_name='Товар'),
        ),
        migrations.AddField(
            model_name='rating_andcomments',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
