# Generated by Django 4.0.3 on 2022-05-24 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0004_rating_andcomments_time_cr'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating_andcomments',
            name='minus',
            field=models.CharField(max_length=255, null=True, verbose_name='Минусы товара'),
        ),
        migrations.AddField(
            model_name='rating_andcomments',
            name='plus',
            field=models.CharField(max_length=255, null=True, verbose_name='Плюсы товара'),
        ),
    ]
